version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/data:/app/data
    environment:
      - UVICORN_WORKERS=1
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
