# CreditWatch Home Assistant Webhook Automation
#
# Import this file into Home Assistant (Settings → Automations & Scenes → Import blueprint)
# to create an automation that listens for webhook calls from the CreditWatch backend.
# Set the ``Webhook ID`` blueprint input to the identifier configured in the backend.
# Update the ``target_map`` dictionary with the notification services that correspond
# to your devices. The backend will send a ``target`` slug that maps to one of these keys.
# Each entry should be a list so multiple notify services can be triggered for a single
# target.
#
# Example: if your mobile device is exposed as ``notify.mobile_app_janes_iphone`` and you
# want it to be the default target, configure the backend with ``default_target: primary``
# and set ``primary`` to a list containing that notify service below.
blueprint:
  name: CreditWatch notification webhook
  description: Handle CreditWatch reminder notifications via a webhook
  domain: automation
  source_url: https://example.com/creditwatch/home-assistant-webhook
  input:
    webhook_id:
      name: Webhook ID
      description: Unique identifier configured in the CreditWatch backend.
      selector:
        text:
      default: creditwatch

trigger:
  - platform: webhook
    allowed_methods:
      - POST
    local_only: false
    webhook_id: !input webhook_id

variables:
  payload: "{{ trigger.json | default({}) }}"
  target_slug: "{{ payload.target | default('default') }}"
  default_target: default
  target_map:
    default:
      - notify.mobile_app_example_device
    # primary:
    #   - notify.mobile_app_primary_phone
    #   - notify.mobile_app_secondary_phone
    # tablet:
    #   - notify.mobile_app_kitchen_tablet
  notify_services: >-
    {% set services = target_map.get(target_slug, target_map.default) %}
    {% if services is string %}
      {{ [services] }}
    {% else %}
      {{ services | list }}
    {% endif %}

condition: []

action:
  - repeat:
      for_each: "{{ notify_services }}"
      sequence:
        - service: "{{ repeat.item }}"
          data:
            title: "{{ payload.title | default('CreditWatch notification') }}"
            message: "{{ payload.message | default('') }}"
            data: "{{ payload.data | default({}) }}"

mode: single
